### ISSUE TITLE
Allow webhook messages through

### ISSUE THREAD

**Issue by qaisjp** [LukeMoll/slack-discord-bridge#4]
We use webhooks to send IRC messages to Discord (which need to be sent to Slack)

Is [this line](https://github.com/HackSoc/slack-discord-bridge/blob/87c08a3f3638fbbddbbee6da94f39a6640f744ad/bot.js#L188) used to prevent the bridge from echo-ing its own messages, or were webhook messages deliberately omitted?

**Comment by LukeMoll** [comment]
It prevents the bridge from echo-ing itself, with the side effect of not forwarding Slack webhooks to Discord (Discord webhooks are forwarded to Slack). I believe this is because there was no way of distinguishing different webhooks on the slack end, although if there is a way do submit a PR 

Your IRC messages should be forwarded to Slack, as we use a similar setup to you, it was fixed in the most recent commit.

**Comment by qaisjp** [comment]
> Your IRC messages should be forwarded to Slack, as we use a similar setup to you, it was fixed in the most recent commit.

Ah, cheers, I've updated it on our side and it works flawlessly now. Cheers!
